version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./database.db:/root/database.db
    environment:
      - DB_DRIVER=sqlite3
      - DB_URL=/root/database.db
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
      - SECRET_KEY=secret